### ISSUE TITLE
Are you still working on this?

### ISSUE THREAD

**Issue by life-coder** [gcallant/Contigo#3]
just wondering

You will receive NO SUPPORT if you do not follow the template below. (Vous ne receverez pas aucune aide si vous effacer ce modèle)

**Server Log:** *(Use [Pastebin](http://pastebin.com/) or [Github Gist](https://gist.github.com/))*

**FML Log(s):** *(Use [Pastebin](http://pastebin.com/) or [Github Gist](https://gist.github.com/))*

**Explanation of issue:**

**How to recreate this issue:**

**Modpack Name:** *(Only if public)*

**Mods Installed:**

**Plugins Installed:**

**Warmroast Report:** *(Optional)*

**Thermos Version:**

**Forge Version:**

**Comment by overclock22** [comment]
I was really hoping one of the branchs would get developed.

**Comment by gcallant** [comment]
Hi,

Thank you both for your interest in Contigo. I apologize for the delay in my response. I am unfortunately very busy (currently finishing up my MS) and have not been able to dedicate enough time to work on this project. I hope to be done soon, however, and return to developing Contigo. In the meantime, I appreciate any additional development contributions on this project, as we could all benefit from a remake. 

Regards,

-Grant
